export const aa = {
  id: 594800,
  resumeUrl: null,
  resumeUploadedAt: null,
  fullAddress: null,
  phoneNumber: "0759149338",
  gender: null,
  race: null,
  email: "gligadumitru98@gmail.com",
  location: null,
  autoApplyDataCompleted: false,
  profilePicture: {
    transform: {
      rect: {
        x: 0,
        y: 0,
        width: 1,
        height: 1,
      },
      zoom: 1,
      angle: 0,
      customBackground: {
        color: null,
        image: null,
      },
    },
    largeUrl:
      "https://s3.resume.io/uploads/career/profile/file/594800/e43134fd617ecca89447399345a7c13a.jpg?version=5bfa1ebc4",
    thumbUrl:
      "https://s3.resume.io/uploads/career/profile/file/594800/thumb_e43134fd617ecca89447399345a7c13a.jpg?version=5bfa1ebc4",
    mediumUrl:
      "https://s3.resume.io/uploads/career/profile/file/594800/medium_squared_e43134fd617ecca89447399345a7c13a.jpg?version=5bfa1ebc4",
    originalUrl:
      "https://s3.resume.io/uploads/career/profile/original_file/594800/17c0c8e2db306762ba0eb39667676069.jpeg",
    blank: false,
  },
  userType: null,
  targetRoles: [],
  currentJobTitle: null,
  targetLocations: [],
  countriesAuthorizedToWorkIn: [],
  hideSkillLevel: false,
  workExperiencesAttributes: [
    {
      id: 1513961,
      title: "Contractor Software Engineer",
      employer: "Betfair",
      city: "Iaşi",
      dateFrom: "2024-04-01",
      dateUntil: null,
      description:
        "<ul>\n  <li><strong>Frontend Development</strong>: Leveraging <strong>React</strong> and <strong>TypeScript</strong> with <strong>Vite</strong> for fast and efficient development. Implementing robust testing practices using <strong>Vitest</strong> to ensure high-quality code and maintainable applications.</li>\n  <li><strong>Backend Development</strong>: Developing scalable and performant backend services using <strong>NestJS</strong>. Utilizing <strong>Kafka</strong> for reliable and high-throughput messaging, <strong>Cassandra</strong> for handling large-scale, distributed data storage, and <strong>Redis</strong> for efficient caching to enhance application performance.</li>\n  <li><strong>System Architecture</strong>: Designing and implementing end-to-end features, ensuring seamless integration between frontend and backend components.</li>\n  <li><strong>Code Quality and Performance</strong>: Writing clean, maintainable code with a focus on performance optimization and best practices.</li>\n  <li><strong>Collaboration and Teamwork</strong>: Working closely with cross-functional teams to deliver high-quality solutions that meet business requirements. I actively participate in code reviews, design discussions, and agile ceremonies.</li>\n  <li><strong>Continuous Learning and Improvement</strong>: Staying up-to-date with the latest industry trends and technologies to continuously improve the development process and the overall quality of the applications.</li>\n</ul>",
      position: 1,
    },
    {
      id: 1513962,
      title: "Senior Software Engineer",
      employer: "3PillarGlobal",
      city: "Iasi",
      dateFrom: "2022-03-01",
      dateUntil: "2024-04-01",
      description:
        "<ul>\n  <li><strong>Contributed to Continuous Improvement</strong> - Enhanced application performance by updating dependencies, reducing load time, and addressing security concerns, in line with a secure, reliable user experience.</li>\n</ul>\n<p><br></p>\n<ul>\n  <li><strong>Agile Project Management: </strong>Actively engaged in cross-functional brainstorming sessions over 3 &nbsp;months to identify process inefficiencies, resulting in the implementation of streamlined procedures and a 20% increase in team productivity.</li>\n</ul>\n<p><br></p>\n<ul>\n  <li><strong>Cross-functional collaboration:</strong> Worked closely with business analysts, development teams, and infrastructure specialists to architect and deliver high-availability solutions.</li>\n</ul>\n<p><br></p>\n<ul>\n  <li><strong>Code Enhancement:</strong> Utilized advanced skills to optimize and refine existing software through code enhancement, successfully eliminating coding errors and improving functionality. This led to a 25% reduction in bug reports and enhanced user experience within 3 development cycles.</li>\n</ul>\n<p><br></p>\n<ul>\n  <li><strong>Testing Proficiency:</strong> Showcased testing proficiency by executing thorough unit tests and &nbsp;End-to-End (E2E) tests, guaranteeing robust software quality and superior performance. This effort contributed to a 20% reduction in post-release issues and enhanced user satisfaction within 3 months using <strong>Jest, Cypress, and Sentry.io.</strong></li>\n</ul>\n<p><br></p>\n<ul>\n  <li><strong>UI Enhancement: </strong>Leveraged advanced tools including <strong>React</strong>, <strong>Redux</strong>, and <strong>Styled-Components</strong> to translate Figma design concepts into polished UI components, &nbsp;optimizing overall system performance and user engagement.</li>\n</ul>\n<p><br></p>\n<ul>\n  <li><strong>Package Management:</strong> Over a dedicated 4-month period, expertly crafted and diligently managed an NPM package for an advanced React-based rich text editor. This endeavor substantially enriched the development landscape by simplifying and accelerating the content creation of articles, effectively reducing feature implementation time and enhancing cross-team collaboration with <strong>NPM</strong>, <strong>React</strong>, and <strong>CKEditor5</strong>.</li>\n</ul>\n<p><br></p>\n<ul>\n  <li><strong>CI/CD pipeline integration: </strong>Over 3 months, adeptly orchestrated an end-to-end CI/CD pipeline for a project encompassing both a&nbsp;React frontend and a microservice API built with Node.js. Seamlessly integrated code base testing, automatic deployment, and production release procedures through the Jenkins pipelines.</li>\n</ul>\n<p><br></p>\n<ul>\n  <li><strong>Technical Interviews and Mentoring:</strong> Over a couple of months, I played a role in cultivating team growth and expertise by participating in technical interviews to assess potential candidates. Additionally, as a dedicated mentor to junior developers, I facilitated knowledge transfer, providing guidance and support that led to an increase in their technical proficiency.</li>\n</ul>",
      position: 2,
    },
    {
      id: 1513963,
      title: "Software Engineer",
      employer: "Levi9",
      city: "Iasi",
      dateFrom: "2021-06-01",
      dateUntil: "2022-03-01",
      description:
        "<ul>\n  <li><strong>Contributed to Continuous Improvement:</strong> Generated valuable suggestions and actively engaged in collaborative problem-solving activities to enhance team performance.</li>\n  <li><strong>Agile Project Management:</strong> Successfully operated within an Agile-driven environment, ensuring adherence to project timelines and optimal resource utilization.</li>\n  <li><strong>Cross-Functional Collaboration:</strong> Worked closely with business analysts, development teams, and infrastructure specialists to architect and deliver high-availability solutions.</li>\n  <li><strong>Code Enhancement:</strong> Applied advanced skills to modify and refine existing software, rectifying coding errors and enhancing functionality.</li>\n  <li><strong>Testing Proficiency:</strong> Conducted meticulous unit tests and End-to-End (E2E) tests, ensuring robust software quality and performance.</li>\n  <li><strong>UI Enhancement:</strong> Elevated user experience by translating provided designs into upgraded UI elements, optimizing overall system performance.</li>\n  <li><strong>JavaScript Expertise:</strong> Adapted and customized JavaScript plugins to align with project requirements and industry best practices.</li>\n  <li><strong>Package Management:</strong> Developed and maintained NPM packages, contributing to an efficient and modular development ecosystem.</li>\n  <li><strong>Technology Stack Mastery:</strong> Demonstrated proficiency across a diverse range of technologies including HTML5, Tailwind CSS, NextJS, ReactJS, GraphQL, Storybook, Jest, Cypress, Git, Jira, and Jenkins.</li>\n  <li><strong>Efficient Multitasking:</strong> Skillfully balanced multiple tasks while fostering seamless collaboration across internal and external teams.</li>\n</ul>",
      position: 3,
    },
    {
      id: 1513964,
      title: "Front-End Developer",
      employer: "Endava",
      city: "Iasi",
      dateFrom: "2019-02-01",
      dateUntil: "2021-06-01",
      description:
        "<ul>\n  <li><strong>Client Collaboration:</strong> Partnered closely with clients throughout development, ensuring seamless integration of required designs.</li>\n  <li><strong>Agile Project Management:</strong> Thrived in an Agile-driven setting, meticulously adhering to project timelines while optimizing resource allocation.</li>\n  <li><strong>Cross-Functional Coordination:</strong> Collaborated closely with business analysts, development teams, and infrastructure specialists, contributing to the delivery of high-availability solutions.</li>\n  <li><strong>Code Enhancement:</strong> Skillfully rectified coding errors by modifying existing software, ensuring code base integrity and functionality.</li>\n  <li><strong>Testing and UI Improvement:</strong> Conducted thorough unit tests, adapting interfaces to provided designs, and driving enhanced system performance.</li>\n  <li><strong>Technologies:</strong> Expertly leveraged a technology stack including HTML5, SCSS, ReactJS, Redux, Jest, Git, Jira, and Jenkins.</li>\n</ul>",
      position: 4,
    },
    {
      id: 1513965,
      title: "UI Developer Intern",
      employer: "Endava",
      city: "Iasi",
      dateFrom: "2018-11-01",
      dateUntil: "2018-12-01",
      description:
        "<ul>\n  <li>Created tasks and communicated deadlines to ensure projects were completed on time.</li>\n  <li>Participated in continuous improvement by generating suggestions, engaging in problem-solving activities to support teamwork.</li>\n  <li>Quickly learned new skills and applied them to daily tasks, improving efficiency and productivity. &nbsp;</li>\n  <li>For 6 weeks I learned the basics of JavaScript, then with the entire team, we created an application for HR people for managing quizzes for new students on summer practice.&nbsp;</li>\n  <li>Technology stack: HTML5, SCSS, ReactJS, Redux, Git, Jira.</li>\n</ul>",
      position: 5,
    },
  ],
  skillsAttributes: [
    {
      id: 5924010,
      skill: "JavaScript",
      level: "experienced",
      position: 1,
    },
    {
      id: 5924011,
      skill: "React",
      level: "experienced",
      position: 2,
    },
    {
      id: 5924012,
      skill: "Node.js",
      level: "experienced",
      position: 3,
    },
    {
      id: 5924013,
      skill: "NextJS",
      level: "skillful",
      position: 4,
    },
    {
      id: 5924014,
      skill: "TypeScript",
      level: "skillful",
      position: 5,
    },
    {
      id: 5924015,
      skill: "Redux",
      level: "beginner",
      position: 6,
    },
    {
      id: 5924016,
      skill: "GraphQL",
      level: "skillful",
      position: 7,
    },
    {
      id: 5924017,
      skill: "ExpressJS",
      level: "skillful",
      position: 8,
    },
    {
      id: 5924018,
      skill: "MongoDB",
      level: "beginner",
      position: 9,
    },
  ],
  educationsAttributes: [
    {
      id: 963469,
      school: "Software Development and Business Information Systems, FEAA",
      degree: "Master Degree",
      city: "Iasi",
      dateFrom: "2021-10-01",
      dateUntil: null,
      description: null,
      position: 1,
    },
    {
      id: 963470,
      school: "Faculty of Computer Science",
      degree: "Bachelor Degree",
      city: "Iasi",
      dateFrom: "2017-09-01",
      dateUntil: "2020-06-01",
      description: null,
      position: 2,
    },
    {
      id: 963471,
      school: 'High School Computer Science "Grigore Moisil"',
      degree: "High School Diploma",
      city: "Iasi",
      dateFrom: "2013-09-01",
      dateUntil: "2017-09-01",
      description: null,
      position: 3,
    },
  ],
  coursesAttributes: [
    {
      id: 344304,
      course:
        "Certification Udemy Complete React Course 2021 (w/ Redux, Hooks, GraphQL)",
      institution: "",
      dateFrom: "2021-02-01",
      dateUntil: "2021-04-01",
      position: 1,
    },
  ],
  socialLinksAttributes: [
    {
      id: 215818,
      title: "Linkedin",
      link: "www.linkedin.com/in/gligadumitru",
    },
    {
      id: 215819,
      title: "Website",
      link: "https://gligadumitru.github.io/portofolio/#/",
    },
    {
      id: 215820,
      title: "Github",
      link: "https://github.com/GligaDumitru",
    },
  ],
  jobPreferenceAttributes: null,
  readyForRecommendations: false,
  resumeType: null,
  resumeId: null,
  autoTailoring: false,
  autoTailoringCl: false,
  newProfile: false,
};
